name: Idea
description: Elixir project idea suggestion
title: "[Idea]: "
labels: ["idea", "triage"]
assignees:
  - Lotes
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this idea suggestion form!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize your idea in one sentence.
      placeholder: |
        For example: Banana-driven realtime database is running as self-financing bitcoin miner.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell the community what your idea is about.
      placeholder: Tell us what you imagine!
    validations:
      required: true
  - type: dropdown
    id: intention
    attributes:
      label: What is the intention or project form of this idea?
      options:
        - Practicing task for yourself
        - Library for developers
        - Application for end-users
    validations:
      required: true
