name: Idea issue was added
on:
  issues:
    types: [opened]

jobs:
  add_idea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
